#!/bin/sh

set -C -f -u
IFS="$(printf '%b_' '\n')"; IFS="${IFS%_}"

# Script arguments
FILE_PATH="${1}"         # Full path of the highlighted file
HEIGHT="${2}"

# Settings
HIGHLIGHT_SIZE_MAX=262143  # 256KiB
HIGHLIGHT_TABWIDTH=8
HIGHLIGHT_STYLE='pablo'

handle_mime() {
    local mimetype="${1}"
    case "${mimetype}" in
        text/html) lynx -width="$4" -display_charset=utf-8 -dump "$1"  ;;
        text/troff) man ./ "${FILE_PATH}" | col -b ;;
        text/* | */xml)
            if [ "$( stat --printf='%s' -- "${FILE_PATH}" )" -gt "${HIGHLIGHT_SIZE_MAX}" ]; then
                exit 2
            fi
            if [ "$( tput colors )" -ge 256 ]; then
                local highlight_format='xterm256'
            else
                local highlight_format='ansi'
            fi
            highlight --replace-tabs="${HIGHLIGHT_TABWIDTH}" --out-format="${highlight_format}" \
                --style="${HIGHLIGHT_STYLE}" --force -- "${FILE_PATH}" ;;
        application/zip) atool --list -- "${FILE_PATH}" ;;
        image/*) mediainfo "${FILE_PATH}" || exit 1;;
        video/* | audio/*|application/octet-stream) mediainfo "${FILE_PATH}" || exit 1;;
        */pdf) pdftotext -l 10 -nopgbrk -q -- "${FILE_PATH}" - ;;
        *opendocument*) odt2txt "$1" ;;
        application/pgp-encrypted) gpg -d -- "$1" ;;
    esac
}

MIMETYPE="$( file --dereference --brief --mime-type -- "${FILE_PATH}" )"
handle_mime "${MIMETYPE}"
exit 1
