#!/bin/sh

# A general, all-purpose extraction script. Not all extraction programs here
# are installed by LARBS automatically.
#
# Default behavior: Extract archive into new directory
# Behavior with `-c` option: Extract contents into current directory

cr="\033[0;0m\033[1;31m"
cg="\033[0;0m\033[1;32m"
cb="\033[0;0m\033[1;34m"

while getopts "hc" o; do case "${o}" in
	c) extracthere="True" ;;
	*) printf "${cg}Options:\\n   -c: Extract archive into current directory rather than a new one.\\n" && exit 1 ;;
esac done

if [ -z "$extracthere" ]; then
	archive="$(readlink -f "$*")" &&
	directory="$(echo "$archive" | sed 's/\.[^\/.]*$//')" &&
	mkdir -p "$directory" &&
	cd "$directory" || exit 1
else
	archive="$(readlink -f "$(echo "$*" | cut -d' ' -f2)" 2>/dev/null)"
fi

[ -z "$archive" ] && printf "${cb}Give archive to extract as argument.\\n" && exit 1

if [ -f "$archive" ] ; then
	case "$archive" in
		*.tar.bz2|*.tbz2) bsdtar -xf "$archive" ;;
		*.tar.xz) bsdtar -xf "$archive" ;;
		*.tar.gz|*.tgz) bsdtar -xf "$archive" ;;
		*.tar.zst) bsdtar -xf "$archive" ;;
		*.tar) bsdtar -xf "$archive" ;;
		*.lzma) unlzma "$archive" ;;
		*.bz2) bunzip2 "$archive" ;;
		*.rar) unrar x -ad "$archive" ;;
		*.gz) gunzip "$archive" ;;
		*.zip) unzip "$archive" ;;
		*.Z) uncompress "$archive" ;;
		*.7z) 7z x "$archive" ;;
		*.xz) unxz "$archive" ;;
		*.exe) cabextract "$archive" ;;
		*) printf "${cr}extract: '%s' - unknown archive method\\n" "$archive" ;;
	esac
else
	printf "${cr}File \"%s\" not found.\\n" "$archive"
fi
