#!/bin/sh

if ifinstalled; then
	ifinstalled unrar unzip || exit
fi

cr="\033[0;0m\033[1;31m"
cg="\033[0;0m\033[1;32m"
cb="\033[0;0m\033[1;34m"
help() { printf "${cg}ex: extract file
Usage: ex ${cb}file${cb}\n"; }
case $1 in
  *.bz2) bunzip2 $1 ;;
  *.deb) ar x $1 ;;
  *.gz) gunzip $1 ;;
  *.rar) unrar x $1 ;;
  *.tar) tar xf  $1 ;;
  *.tar.bz2) tar xjf $1 ;;
  *.tar.gz) tar xzf $1 ;;
  *.tar.xz) tar xf  $1 ;;
  *.tar.zst) unzstd $1 ;;
  *.tbz2) tar xjf $1 ;;
  *.tgz) tar xzf $1 ;;
  *.zip) unzip $1 ;;
  *.Z) uncompress $1 ;;
  *.7z) 7za e $1 ;;
  *.*) printf "${cr} '$1' cannot be extracted.\n" ;;
  *) help;;
esac
